name: Build and Deploy

# Only run on pushes to main or manual triggers
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**README.md'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # TODO: Create a docker container that has all the dependencies already installed
    - name: Install chrome
      uses: browser-actions/setup-chrome@v1
      with:
        install-dependencies: true

    - name: Install build tools
      run: |
        sudo apt-get update && \
        sudo apt-get install -y \
          gpp \
          pandoc \

    - name: Build resume
      run: ./build.sh

    - name: Prepare for pages
      run: |
        mkdir -p _site
        cp build/resume-public.html _site/index.html
        cp build/resume-private.pdf _site/resume.pdf
        cp style.css _site/style.css

    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v3.0.1

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
